### ISSUE TITLE
Incorrect value in SF Mission

### ISSUE THREAD

**Issue by jlebar** [skalnik/aqi-wtf#6] opened 2020-09-06 07:25 UTC
Site is saying AQI is 30 rn, but it is very smoky in the SF Mission, and this is reflected on PurpleAir.

Either you're getting the wrong location (seems unlikely, geolocation seems to work correctly on other sites) or maybe you're not excluding indoor sensors?

**Comment by skalnik** [comment] 2020-09-06 21:20
Closing as duplicate of https://github.com/skalnik/aqi-wtf/issues/7, which has more conversation about this. Feel free to reopen if that explanation doesn't seem to line up!

**Closed as completed by skalnik** 2020-09-06 21:20 UTC
